; retractprobe.g
; called to retract a physical Z probe
;
; generated by RepRapFirmware Configuration Tool v2.1.4 on Thu Dec 19 2019 10:08:29 GMT-0600 (Central Standard Time)
M280 P0 S90 ; retract BLTouch
